### ISSUE TITLE
Add multi denom support

### ISSUE THREAD

**Issue by marbar3778** [tendermint/faucet#7]
## Summary

In many cases a chain will not only have one token they will want to add to a fauct. In these scenarios it forces the user of this software to run many instances of this software. 

Add support for multiple denoms. A user can send their address and the denom they would like sent.

**Comment by fadeev** [comment]
@helder-moreira has this been closed, perhaps, because this functionality already exists in the faucet?

**Comment by helder-moreira** [comment]
@fadeev yes the functionality was already on starport, but the app on this repo did not allow configuring multiple default denoms. Now it has been updates to support it.
